name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
      with:
        go-version-file: ./go.mod
        cache-dependency-path: ./go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
